modLoader="javafml"
loaderVersion="[43,)"
license="GNU LGPLv3"

[[mods]]
    modId="staywarmtogether"
    version="19.2.0.4"
    displayName="Stay Warm Together"
    authors="skyjay1 and VoutVouniern"
    description='''MMD Winterjam 2022'''

[[dependencies.staywarmtogether]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.7,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.staywarmtogether]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1.36,)"
    ordering="NONE"
    side="BOTH"
